import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen grid grid-cols-1 md:grid-cols-2">
      <div className="flex flex-col items-center justify-center">{children}</div>
      <div className="hidden md:block bg-[url('/banner-login.png')] bg-no-repeat bg-cover bg-center w-full" />
    </div>
  );
}
